"""migrate

Revision ID: f1d0ba6a99a2
Revises: 246b499f543b
Create Date: 2022-05-20 16:49:11.879223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d0ba6a99a2'
down_revision = '246b499f543b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_description')
    # ### end Alembic commands ###
